title: Arin Bhandari
author:
  name: Arin Bhandari
  email: arin.bhandari AT gmail.com
# Build settings
theme: minima
plugins:
  - jekyll-feed

minima:
  social-links:
    - title: Linkedin
      icon: linkedin
      url: "https://www.linkedin.com/in/arin-bhandari"